import { PartialDictItem } from './dict';

export const mond: PartialDictItem[] = [
  { hiragana: 'でからびあん', word: 'デカラビアン' },
  { hiragana: 'ばるばとす', word: 'バルバトス' },
  { hiragana: 'あんどりあす', word: 'アンドリアス' },
  { hiragana: 'あんばー', word: 'アンバー' },
  { hiragana: 'がいあ', word: 'ガイア' },
  { hiragana: 'りさ', word: 'リサ' },
  { hiragana: 'ばーばら', word: 'バーバラ' },
  { hiragana: 'ぺっち', word: 'ペッチ', note: 'ファミリーネーム' },
  { hiragana: 'れざー', word: 'レザー' },
  { hiragana: 'ふぃっしゅる', word: 'フィッシュル' },
  { hiragana: 'べねっと', word: 'ベネット' },
  { hiragana: 'のえる', word: 'ノエル' },
  { hiragana: 'すくろーす', word: 'スクロース' },
  { hiragana: 'じん', word: 'ジン' },
  { hiragana: 'ぐんひるど', word: 'グンヒルド', note: 'ファミリーネーム' },
  { hiragana: 'でぃるっく', word: 'ディルック' },
  { hiragana: 'らぐゔぃんど', word: 'ラグヴィンド', note: 'ファミリーネーム' },
  { hiragana: 'もな', word: 'モナ' },
  { hiragana: 'うぇんてぃ', word: 'ウェンティ' },
  { hiragana: 'くれー', word: 'クレー' },
  { hiragana: 'どどこ', word: 'ドドコ' },
  { hiragana: 'ありす', word: 'アリス' },
  { hiragana: 'でぃおな', word: 'ディオナ' },
  { hiragana: 'あるべど', word: 'アルベド' },
  { hiragana: 'れいんどっと', word: 'レインドット' },
  { hiragana: 'ろさりあ', word: 'ロサリア' },
  { hiragana: 'えうるあ', word: 'エウルア' },
  { hiragana: 'ろーれんす', word: 'ローレンス', note: 'ファミリーネーム' },
  { hiragana: 'ろざりん・くるーずちか・ろーえふぁるた', word: 'ロザリン・クルーズチカ・ローエファルタ' },
  { hiragana: 'ろざりん', word: 'ロザリン' },
  { hiragana: 'くるーずちか', word: 'クルーズチカ' },
  { hiragana: 'ろーえふぁるた', word: 'ローエファルタ' },
  { hiragana: 'ゔぁねっさ', word: 'ヴァネッサ', note: 'ムラタ人だが便宜上ここに記載' },
  { hiragana: 'えばはーと', word: 'エバハート' },
  { hiragana: 'ぱるじふぁる', word: 'パルジファル' },
  { hiragana: 'えれんどりん', word: 'エレンドリン' },
  { hiragana: 'るーすたん', word: 'ルースタン' },
  { hiragana: 'ちぞめのきし', word: '血染めの騎士' },
  { hiragana: 'ふぁるか', word: 'ファルカ' },
];

export const riyue: PartialDictItem[] = [
  { hiragana: 'しゃんりん', word: '香菱' },
  { hiragana: 'ぐぅおぱぁー', word: 'グゥオパァー' },
  { hiragana: 'ほくと', word: '北斗' },
  { hiragana: 'ゆくあき', word: '行秋' },
  { hiragana: 'ぎょうこう', word: '凝光' },
  { hiragana: 'ちょううん', word: '重雲' },
  { hiragana: 'なな', word: '七七' },
  { hiragana: 'びゃくじゅつ', word: '白朮' },
  { hiragana: 'こくせい', word: '刻晴' },
  { hiragana: 'りゅううんしゃくふうしんくん', word: '留雲借風真君' },
  { hiragana: 'さくげつちくようしんくん', word: '削月築陽真君' },
  { hiragana: 'りすいじょうざんしんくん', word: '理水畳山真君' },
  { hiragana: 'しんえん', word: '辛炎' },
  { hiragana: 'しょうり', word: '鍾離' },
  { hiragana: 'がんおうていくん', word: '岩王帝君' },
  { hiragana: 'きしゅう', word: '帰終' },
  { hiragana: 'かんう', word: '甘雨' },
  { hiragana: 'しょう', word: '魈' },
  { hiragana: 'こうまたいせい', word: '降魔大聖' },
  { hiragana: 'ごほうやしゃ', word: '護法夜叉' },
  { hiragana: 'どうじゃく', word: '銅雀' },
  { hiragana: 'ふーたお', word: '胡桃' },
  { hiragana: 'えんひ', word: '煙緋' },
  { hiragana: 'よぉーよ', word: 'ヨォーヨ' },
  { hiragana: 'あつこ', word: '竺子' },
  { hiragana: 'げんしょう', word: '言笑' },
  { hiragana: 'こうせつ', word: '江雪' },
  { hiragana: 'ぴんばあや', word: 'ピンばあや' },
  { hiragana: 'ほうじ', word: '宝児' },
  { hiragana: 'しんかく', word: '申鶴' },
  { hiragana: 'うんきん', word: '雲菫' },
  { hiragana: 'おせる', word: 'オセル' },
  { hiragana: 'ばっせい', word: '跋掣', note: 'オセルの妻' },
  { hiragana: 'へうりあ', word: 'ヘウリア' },
  { hiragana: 'まるこしあす', word: 'マルコシアス', note: '力を失う前のグゥオパァー' },
];

export const inazuma: PartialDictItem[] = [
  { hiragana: 'かみさと', word: '神里' },
  { hiragana: 'あやか', word: '綾華' },
  { hiragana: 'かみさとあやか', word: '神里綾華' },
  { hiragana: 'あやと', word: '綾人' },
  { hiragana: 'かみさとあやと', word: '神里綾人' },
  { hiragana: 'かえではら', word: '楓原' },
  { hiragana: 'かずは', word: '万葉' },
  { hiragana: 'かえではらかずは', word: '楓原万葉' },
  { hiragana: 'さゆ', word: '早柚' },
  { hiragana: 'よいみや', word: '宵宮' },
  { hiragana: 'らいでんしょうぐん', word: '雷電将軍' },
  { hiragana: 'らいでんえい', word: '雷電影' },
  { hiragana: 'えい', word: '影' },
  { hiragana: 'らいでんまこと', word: '雷電眞' },
  { hiragana: 'さら', word: '裟羅' },
  { hiragana: 'くじょうさら', word: '九条裟羅' },
  { hiragana: 'さんごのみや', word: '珊瑚宮' },
  { hiragana: 'ここみ', word: '心海' },
  { hiragana: 'さんごのみやここみ', word: '珊瑚宮心海' },
  { hiragana: 'とーま', word: 'トーマ' },
  { hiragana: 'ごろー', word: 'ゴロー' },
  { hiragana: 'やえみこ', word: '八重神子' },
  { hiragana: 'しかのいんへいぞう', word: '鹿野院平蔵' },
  { hiragana: 'しかのいん', word: '鹿野院' },
  { hiragana: 'へいぞう', word: '平蔵' },
  { hiragana: 'おろばし', word: 'オロバシ' },
  { hiragana: 'おろばしのみこと', word: 'オロバシノミコト' },
  { hiragana: 'きつねさいぐう', word: '狐斎宮' },
  { hiragana: 'みこしちよ', word: '御輿千代' },
  { hiragana: 'ささゆり', word: '笹百合' },
  { hiragana: 'はなちるさと', word: '花散里' },
  { hiragana: 'あさせひびき', word: '浅瀬響' },
  { hiragana: 'かむなはるのすけ', word: '惟神晴之介' },
  { hiragana: 'はるのすけ', word: '晴之介' },
  { hiragana: 'うらくさい', word: '有楽斎' },
  // { hiragana: 'あらたきいっと', word: '荒瀧一斗' },
  { hiragana: 'まさのり', word: '公義' },
  { hiragana: 'ねこ', word: '寝子' },
  { hiragana: 'えんじょう', word: '淵上' },
  { hiragana: 'ざんひょう', word: '散兵' },
];

export const sumeru: PartialDictItem[] = [
  { hiragana: 'くらくさなりでび', word: 'クラクサナリデビ' },
  { hiragana: 'せの', word: 'セノ' },
  { hiragana: 'こな', word: 'コナ' },
];

export const snezhnaya: PartialDictItem[] = [
  { hiragana: 'たるたりや', word: 'タルタリヤ' },
  { hiragana: 'しにょーら', word: 'シニョーラ' },
  { hiragana: 'すからましゅ', word: 'スカラマシュ' },
];

export const khaenriah: PartialDictItem[] = [
  { hiragana: 'だいんすれいゔ', word: 'ダインスレイヴ' },
];
