import { PartialDictItem } from './dict';

export const teyvat: PartialDictItem[] = [
  { hiragana: 'しちてんじんぞう', word: '七天神像' },
  { hiragana: 'せんれい', word: '仙霊' },
  { hiragana: 'ここなっつひつじ', word: 'ココナッツヒツジ' },
  { hiragana: 'ふぁでゅい', word: 'ファデュイ' },
  { hiragana: 'ほうとうだん', word: '宝盗団' },
  { hiragana: 'かいとうさい', word: '海灯祭' },
  { hiragana: 'つきおいさい', word: '月逐い祭' },
  { hiragana: 'ばどるどー', word: 'バドルドー' },
  { hiragana: 'かみのめ', word: '神の眼' },
  { hiragana: 'いのちのせいざ', word: '命ノ星座' },
  { hiragana: 'かみさくら', word: '神櫻' },
  { hiragana: 'うんかんしゃ', word: 'うんかんしゃ' },
];

export const enemy: PartialDictItem[] = [
  { hiragana: 'らいけいじゅつし', word: '雷蛍術師' },
  { hiragana: 'ひょうけいじゅつし', word: '氷蛍術士' },
  { hiragana: 'むそうのかぜ', word: '無相の風' },
  { hiragana: 'むそうのいかずち', word: '無相の雷' },
  { hiragana: 'むそうのこおり', word: '無相の氷' },
  { hiragana: 'むそうのいわ', word: '無相の岩' },
  { hiragana: 'むそうのほのお', word: '無相の炎' },
  { hiragana: 'むそうのみず', word: '無相の水' },
  { hiragana: 'ばくえんじゅ', word: '爆炎樹' },
  { hiragana: 'きゅうとうじゅ', word: '急凍樹' },
  { hiragana: 'じゅんすいせいれい', word: '純水精霊' },
  { hiragana: 'ろーでしあ', word: 'ローデシア' },
  { hiragana: 'ゔぃしゃっぷ', word: 'ヴィシャップ' },
  { hiragana: 'えんしぇんとゔぃしゃっぷ', word: 'エンシェントヴィシャップ' },
  { hiragana: 'じゃくだりゅうおう', word: '若陀龍王' },
  { hiragana: 'あびすのしと', word: 'アビスの使徒' },
  { hiragana: 'まぐうけんき', word: '魔偶剣鬼' },
  { hiragana: 'かいらぎ', word: '海乱鬼' },
  { hiragana: 'いせききへい', word: '遺跡機兵' },
  { hiragana: 'ふらいむ', word: 'フライム' },
  { hiragana: 'らいおんごんげん', word: '雷音権現' },
  { hiragana: 'じゅういき', word: '獣域' },
  { hiragana: 'うぇるぷ', word: 'ウェルプ' },
  { hiragana: 'じゅういきうぇるぷ', word: '獣域ウェルプ' },
  { hiragana: 'じゅういきはうんど', word: '獣域ハウンド' },
];